apiVersion: v1
kind: Namespace
metadata:
  name: aws-xray
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: xray-daemon
  namespace: aws-xray
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/CLUSTER_NAME-xray-daemon
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: xray-daemon
  namespace: aws-xray
spec:
  selector:
    matchLabels:
      app: xray-daemon
  template:
    metadata:
      labels:
        app: xray-daemon
    spec:
      serviceAccountName: xray-daemon
      containers:
      - name: xray-daemon
        image: public.ecr.aws/xray/aws-xray-daemon:latest
        command:
        - /usr/bin/xray
        - -o
        - -n
        - ap-northeast-2
        resources:
          limits:
            cpu: 256m
            memory: 32Mi
          requests:
            cpu: 256m
            memory: 32Mi
        ports:
        - name: xray-ingest
          containerPort: 2000
          hostPort: 2000
          protocol: UDP
        - name: xray-tcp
          containerPort: 2000
          hostPort: 2000
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: xray-service
  namespace: aws-xray
spec:
  selector:
    app: xray-daemon
  clusterIP: None
  ports:
  - name: xray-ingest
    port: 2000
    protocol: UDP
  - name: xray-tcp
    port: 2000
    protocol: TCP