apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: savemypodo-app
  namespace: monitoring 
  labels:
    app: savemypodo-app
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: savemypodo-app
  namespaceSelector:
    matchNames:
      - default
  endpoints:
  - port: http
    path: /actuator/prometheus
    interval: 15s
    scrapeTimeout: 10s