apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: savemypodo-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: savemypodo-app-deployment
  minReplicas: 2
  maxReplicas: 5
