apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: savemypodo-dev
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  source:
    path: manifests/overlays/dev
    repoURL: https://github.com/CLD-3rd/team2-infra
    targetRevision: dev
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
